### ISSUE TITLE
[Bug] Error e.apply is not a function

### ISSUE THREAD

**Issue by RASK18** [BossSloth/SteamHunter-plugin#28]
### Describe the Bug

I’ve just installed Millennium for the first time, and when I try to use this plugin, I get this error: 

<img width="1059" height="551" alt="Image" src="https://github.com/user-attachments/assets/97a658a0-7ad5-4a71-8bce-362f7a56d565" />

### Plugin Version

v2.1.0

### Millennium Version

v2.36.1

### Operating System

Windows

### Expected Behavior

View achievement groups

### Actual Behavior

Error e.apply is not a function

### Reproducibility

- [ ] Yes, I can reproduce this issue consistently

### Steps To Reproduce

1. Install Millennium
2. Install this plugin via Millennium (using the ID)
3. Millennium will ask you to restart Steam
4. Open the achievements for any game

**Comment by Tsukemono-0** [comment]
<img width="971" height="1063" alt="Image" src="https://github.com/user-attachments/assets/7cf069cc-0a84-4423-a060-daa084c7c5e9" />

I get the same error now, but if I go to the store page and then click on view achievements it works, also when in games Achievements groups is not there or it is but its just a spinning wheel/cog as if its loading but never loads.

**Comment by HitagiSenjougaharaFFXIV** [comment]
No Achievement groups 

<img width="1251" height="789" alt="Image" src="https://github.com/user-attachments/assets/03a7f91b-c139-442b-94e0-daeea0fe0111" />

**Comment by wheredaud** [comment]
<img width="718" height="609" alt="Image" src="https://github.com/user-attachments/assets/0d3b3d28-8b88-4483-b622-9dc8f6d8794b" />
For me the plugin has been broken for almost all of may and looks this on every game.

**Comment by ishuval** [comment]
<img width="852" height="467" alt="Image" src="https://github.com/user-attachments/assets/2c749f62-e09e-4941-879e-8e5e2c8675f5" /> 
I also cannot see achievement groups on any game for several weeks

**Comment by BossSloth** [comment]
## Achievement groups currently only works on the [Millennium 3.0 beta](https://github.com/SteamClientHomebrew/Millennium/releases) due to a bug with millennium.
Either install the Millennium 3.0 beta or wait until 3.0 becomes stable.

**Comment by BossSloth** [comment]
Since Millennium 3.0 stable has been released for a while, I'm closing this issue
